Implement Prisma
NewCircuit/modmail pull request #14
Opened 2022-04-01 23:37 UTC by dylhack

2022-04-01 23:42 UTC, dylhack commented
waiting for: #15

2022-04-02 06:59 UTC, dylhack commented
This is not ready for review until it is out of draft

2022-04-02 20:25 UTC, AltF02 requested changes

2022-04-02 20:25 UTC, AltF02 commented on scripts/build.sh
> +
use package.json scripts

2022-04-02 20:25 UTC, dylhack commented
@AltF02 Could you add more tests to the todo list?

2022-05-16 02:20 UTC, closed without merging